apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobs-pvc
  namespace: async-doctor
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  # GKE Autopilot: prefer standard-rwo
  storageClassName: standard-rwo
