apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: async-doctor
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector: { app: async-doctor, tier: web }
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
